name: 'Srg auto collect changelog'
description: 'Auto collect changelog'
inputs:
  jira-domain:  # id of input ddd
    description: 'The company Jira domain'
    required: true
    default: 'srgxxxx.atlassian.net'
outputs:
  jira_ticket_list:
    description: "The jira tickets list form pull request and commit message"
    value: ${{ steps.extract_jira_tickets.outputs.jira_ticket_list }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.jira_domain }}.
      shell: bash
    - id: extract_jira_tickets
      run: |
        echo "jira_ticket_list=$(echo abc-$RANDOM)" >> $GITHUB_OUTPUT
        echo " hello extract_jira_tickets step"

      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: echo "${{ toJSON(github) }}"
      shell: bash
    - run: echo "dump test"
      shell: bash
    
    - run: pwd
      shell: bash
    
    - run: goodbye.sh
      shell: bash
