# --------------------------------------------------------------------------------------------------
# Input: jira_domain, gh_token, and trigger keywords
# Process: 
# 1, extract jira ticket from dev's branch name, commits, pull request title, and pull request body
# 2, extract commit based git commit convention with: fix:feat:chore convention
# 3, append and inject the jira_domain into jira ticket of the step 2 in markdown format
# 4, check if trigger keywords are in pull request title or body. (Optional)
# Output: jira_tickets_list and absolute path of changelog.md 
# --------------------------------------------------------------------------------------------------
name: 'Srg auto collect changelog'
description: 'Auto collect changelog'
inputs:
  jira_domain:
    description: 'The company Jira domain'
    required: true
    default: 'srgxxxx.atlassian.net'
  gh_token:
    description: 'A Github token with read permission for repos'
    required: true
outputs:
  jira_ticket_list:
    description: "The jira tickets list form pull request and commit message"
    value: ${{ steps.export_outputs_step.outputs.jira_ticket_list }}
  srg_test_output:
    description: "Test Github action output"
    value: ${{ steps.export_outputs_step.outputs.srg_test_output }}
  srg_changelog_file:
    description: "The file that contains changelog of current pull request"
    value: ${{ steps.export_outputs_step.outputs.srg_changelog_file }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.jira_domain }}.
      shell: bash

    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    # - run: echo "${{ toJSON(github) }}"
    #   shell: bash

    - run: pwd
      shell: bash

    - run: |
        echo name: "AAA -> Figure out env --> 0: Pr event type"
        echo ""

        echo "github event action: ${{github.event.action}}"
        if [[ "${{ github.event_name }}" == 'pull_request' && "${{github.event.pull_request.merged}}" == 'true' && "${{github.event.action}}" == 'closed' ]]; then
          echo "----------------------------> PR merged and closed. <----------------------------"
          echo "PR_STATE=CLOSED_AND_MERGED" >> $GITHUB_ENV
        elif [[ "${{ github.event_name }}" == 'pull_request' && "${{github.event.pull_request.merged}}" == 'false' && "${{github.event.action}}" == 'closed' ]]; then
          echo "----------------------------> PR closed without merging, do nothing. <----------------------------"
          echo "PR_STATE=CLOSED_BUT_NOT_MERGED" >> $GITHUB_ENV
        else
          echo "----------------------------> PR event action:${{github.event_name}} <----------------------------"
          echo "PR_STATE=COMMIT_PUSH" >> $GITHUB_ENV
        fi
      shell: bash

    - run: |
        echo name: "AAA -> Figure out Rnv --> 0: Test srcipt"
        echo ""
        goodbye.sh
      shell: bash

    - run: |
        echo "AAA -> Init env --> 1: Init file name into GITHUB_ENV"
        echo ""
        echo "SRG_PR_CONTENT_TXT=srg_temp_pr_and_branch_info.txt" >> $GITHUB_ENV
        echo "SRG_TEMP_FILE=srg_temp.txt" >> $GITHUB_ENV
        echo "SRG_COMMITS_FILE=srg_temp_commits.txt" >> $GITHUB_ENV
        echo "SRG_OUTPUT_CHANGLOG_FILE=srg_output_changelog.md" >> $GITHUB_ENV
        echo "SRG_OUTPUT_TICKETS_FILE=srg_output_tickets.txt" >> $GITHUB_ENV
        echo "SRG_OUTPUT_COMMITS_FILE=srg_output_commits.txt" >> $GITHUB_ENV
      shell: bash

    - run: |
        echo "AAA -> init env --> 2: Get repo company name"
        echo ""
        repo_org_name=$(get_repo_company_name.sh "SrgGactionChangelogApp")
        echo "repo_org_name --> $repo_org_name"
      shell: bash

    - run: |
        echo "CCC -> Get commits --> 0: save commit message to text"
        echo ""
        PR_NUMBER="${{ github.event.pull_request.number }}"
        REPO_NAME="${{ github.repository }}"
        API_URL="https://api.github.com/repos/$REPO_NAME/pulls/$PR_NUMBER/commits"
 
        curl -s -H "Authorization: token ${{ inputs.gh_token }}" -H "Accept: application/vnd.github+json" $API_URL > "${{ env.SRG_TEMP_FILE}}"

        PR_MERGED="${{ github.event.pull_request.merged }}"
        if [ "$PR_MERGED" = "true" ]; then
          jq_installed=$(command -v jq)
          if [ -z "$jq_installed" ]; then
            echo "jq is not installed on the machie, exit..." 
            exit 1
          fi

          cat "./${{ env.SRG_TEMP_FILE}}"
          echo "---------------------------------------------"
          cat "./${{ env.SRG_TEMP_FILE}}" | jq -r '.[] | "\(.commit.message)"' > "./${{ env.SRG_COMMITS_FILE }}"
          cat "./${{ env.SRG_COMMITS_FILE }}"

        else
          echo "Pull request was not merged, unable to retrieve commits."
        fi
      if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true }}
      shell: bash

    - if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true }}
      uses: DamianReeves/write-file-action@master
      with:
        path: "./${{ env.SRG_PR_CONTENT_TXT }}"
        contents: |
          ${{ github.head_ref }}
          ${{ github.event.pull_request.title }}
          ${{ github.event.pull_request.body }}
        write-mode: overwrite

    - if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true }}
      id: export_outputs_step
      run: |
        echo "extract jira ticket from pr and commits"
        echo ""
        pwd
        pwd=$(pwd)
        echo "pwd -> $pwd"
        srg_changelog_abs_path="$(pwd)/${{ env.SRG_OUTPUT_CHANGLOG_FILE }}"
        echo "jira_ticket_list=$(echo abc-$RANDOM)" >> $GITHUB_OUTPUT
        echo "srg_changelog_file=$srg_changelog_abs_path" >> $GITHUB_OUTPUT
        echo "srg_test_output=Hello_output_gaction" >> $GITHUB_OUTPUT
      shell: bash

    - run: |
        echo "WWW -> Cat Files --> 0: txt files"
        echo ""
        pattern_commit_convention="feat|fix|ci|chore|docs"
        pattern_jira_tickets="([a-z]{2,}-)([0-9]+)"

        echo "------------------ cat ${{ env.SRG_COMMITS_FILE }} --------------------"
        cat "${{ env.SRG_COMMITS_FILE }}"

        echo "------------------ extract commit message --------------------"
        cat "${{ env.SRG_PR_CONTENT_TXT }}" | grep -i -E "(${pattern_commit_convention}):" | sort -u | sort -n |sed -e 's/([^()]*)//g' > "${{ env.SRG_OUTPUT_COMMITS_FILE }}" 
        cat "${{ env.SRG_COMMITS_FILE }}" | grep -i -E "(${pattern_commit_convention}):" | sort -u | sort -n |sed -e 's/([^()]*)//g' >> "${{ env.SRG_OUTPUT_COMMITS_FILE }}"
        cat "${{ env.SRG_OUTPUT_COMMITS_FILE }}"
        echo "uuuuuuuuuuuuuu"
        cat "${{ env.SRG_OUTPUT_COMMITS_FILE }}" | sort -u | sort -n > temp.txt && mv temp.txt ${{ env.SRG_OUTPUT_COMMITS_FILE }}
        cat "${{ env.SRG_OUTPUT_COMMITS_FILE }}"

        echo "------------------ extract jira ticket --------------------"
        cat "${{ env.SRG_PR_CONTENT_TXT }}" "${{ env.SRG_COMMITS_FILE }}" | grep -Eo "${pattern_jira_tickets}" | sort -u | sort -n > "${{ env.SRG_OUTPUT_TICKETS_FILE }}"
        # cat "${{ env.SRG_COMMITS_FILE }}" | grep -Eo "${pattern_jira_tickets}" | sort -u | sort -n >> "${{ env.SRG_OUTPUT_TICKETS_FILE }}"
        cat "${{ env.SRG_OUTPUT_TICKETS_FILE }}"
        echo "uuuuuuuuuuuuuu"
        cat "${{ env.SRG_OUTPUT_TICKETS_FILE }}" | sort -u | sort -n > temp.txt && mv temp.txt ${{ env.SRG_OUTPUT_TICKETS_FILE }}
        cat "${{ env.SRG_OUTPUT_TICKETS_FILE }}"


      shell: bash
      if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true }}
    - run: |
        echo "XXX -> Echo --> 0: txt files"
        echo ""
        pwd="$(pwd)"
        echo "${pwd}/${{ env.SRG_OUTPUT_CHANGLOG_FILE }}"
        cat "${pwd}/${{ env.SRG_OUTPUT_CHANGLOG_FILE }}"
        echo "-----------------------------------------------------"
        echo "${pwd}/${{ env.SRG_OUTPUT_TICKETS_FILE }}"
        cat "${pwd}/${{ env.SRG_OUTPUT_TICKETS_FILE }}"
        echo "-----------------------------------------------------"
        echo "${pwd}/${{ env.SRG_OUTPUT_COMMITS_FILE }}"
        cat "${pwd}/${{ env.SRG_OUTPUT_COMMITS_FILE }}"
        echo "-----------------------------------------------------"
      shell: bash
    - run: |
        echo "ZZZ -> Clean up --> 0: txt files"
        echo ""
        echo "------------- pull_request closed and merged ------------"
        rm -f "${{ env.SRG_PR_CONTENT_TXT }}"
        rm -f "${{ env.SRG_TEMP_FILE }}"
        rm -f "${{ env.SRG_COMMITS_FILE }}"
      shell: bash