on:
  pull_request:
    branches:
      - main
      - develop
      - release/*
    types: [ closed, opened, reopened, draft ]
    # draft: change ticket status to in progress
    # opened/reopened: attach apk to ticket
    # closed: attach pr link to tikcet

jobs:
  generate_changelog:
    runs-on: [ ubuntu-latest ]
    name: "Generate changelog from PR"
    steps:
      - id: collect_jira_tickets_in_pr
        continue-on-error: true
        uses: SweetRainGarden/SrgGactionChangelogApp@release/1.0.0
        with:
          jira_domain: 'xxx.atlassian.net'

          gh_token: "${{ secrets.ORG_SECRET_CI_TOKEN }}"
          google_sheet_token: "${{ secrets.ANDROID_CI_GSHEET_PRIVATE_KEY }}"
          google_sheet_client_email: "${{ secrets.ANDROID_CI_GSHEET_CLIENT_EMAIL }}"
          google_sheet_id: "1B95QAymjwitZotDcwQrQISoA7sYXmSe0thoUupQ48e4"
          google_sheet_work_sheet_title: "changelog_from_pr"
      
      - name: "Print outputs from SrgGactionChangelogApp"
        run: | 
          echo "jira_ticket_list ---> ${{ steps.collect_jira_tickets_in_pr.outputs.jira_ticket_list }}"
          echo "srg_changelog_file ---> ${{ steps.collect_jira_tickets_in_pr.outputs.srg_changelog_file }}"
          echo "srg_test_output ---> ${{ steps.collect_jira_tickets_in_pr.outputs.srg_test_output }}"
          echo "PR_STATE env: ---> ${{ env.PR_STATE }}"
          echo "BASH_ENV env: ---> ${{ env.BASH_ENV }}"
        shell: bash
