on:
  pull_request:
    branches:
      - main
      - develop
      - release/*
    types: [ closed, opened, reopened, draft ]
    # draft: change ticket status to in progress
    # opened/reopened: attach apk to ticket
    # closed: attach pr link to tikcet

jobs:
  hello_world_job:
    runs-on: [ ubuntu-latest ]
    name: "Test SrgGactionChangelogApp"
    steps:
      - id: collect_jira_tickets_in_pr
        uses: SweetRainGarden/SrgGactionChangelogApp@develop
        with:
          jira_domain: 'xxx.atlassian.net'
          gh_token: "${{ secrets.ORG_SECRET_CI_TOKEN }}"
      - run: | 
          echo random-number ${{ steps.collect_jira_tickets_in_pr.outputs.jira_ticket_list }}
          echo "PR_STATE env: ---> ${{ env.PR_STATE }}"
          echo "BASH_ENV env: ---> ${{ env.BASH_ENV }}"
        shell: bash
