on:
  push:
    branches:
      - main
      - develop
      - release/*
  pull_request:
    branches:
      - main
      - develop
      - release/*
    types: [ closed ]

jobs:
  hello_world_job:
    runs-on: [ ubuntu-latest ]
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: SweetRainGarden/SrgGactionChangelogApp@develop
        with:
          jira-domain: 'xxx.atlassian.net'
      - run: echo random-number ${{ steps.foo.outputs.jira_ticket_list }}
        shell: bash
